export default {
  ADD_TODO: 'ADD_TODO',
  DELETE_TODO: 'DELETE_TODO',
  DELETE_TODO_COMPLETED: 'DELETE_TODO_COMPLETED',
  CHANGE_FILTER: 'CHANGE_FILTER',
  UPDATE_TODO: 'UPDATE_TODO',
  TOGGLE_EDIT: 'TOGGLE_EDIT',
}
